[toolchain]
anchor_version = "0.30.0" # `anchor-cli` version to use
solana_version = "1.18.8" # Solana version to use

[features]
resolution = true
skip-lint = false

# Production ----------------------------------------------------------------
# [programs.mainnet]
# fjord_lbp = "fjorR4ubuG42xkRUF6SrA1hKkb1T4LqgfupE1mPLK4K"
# ---------------------------------------------------------------------------

# Dev -----------------------------------------------------------------------
[programs.devnet]
fjord_lbp = "HSbvUZ5aSBSUteCEmvyspZd85YCy3pgofX7dyLf844iw"
# ---------------------------------------------------------------------------

# Local ---------------------------------------------------------------------
# [programs.localnet]
# fjord_lbp = "9rxayE6EkqWvCfdyQ41VHRNPoV97dVKdXDUuQYAqurKh"
# ---------------------------------------------------------------------------

[registry]
url = "https://api.apr.dev"

[provider]
# Path to the wallet keypair to use for deployments/upgrades

# Production ----------------------------------------------------------------
# wallet = "./deployment-keypair/production/id.json" 
# cluster = "Mainnet"
# ---------------------------------------------------------------------------

# Dev -----------------------------------------------------------------------
wallet = "./deployment-keypair/development/id.json"
cluster = "Devnet"
# ---------------------------------------------------------------------------

# Local ---------------------------------------------------------------------
# wallet = "./deployment-keypair/local/id.json"
# cluster = "Localnet"
# ---------------------------------------------------------------------------

[workspace]
types = "types"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
upgradeable = true