[toolchain]
anchor_version = "0.29.0" # `anchor-cli` version to use
solana_version = "1.17.28" # Solana version to use

[features]
seeds = true
skip-lint = false

# Production ----------------------------------------------------------------
# [programs.mainnet]
# fjord_lbp = "fjorR4ubuG42xkRUF6SrA1hKkb1T4LqgfupE1mPLK4K"
# ---------------------------------------------------------------------------

# Dev -----------------------------------------------------------------------
# [programs.devnet]
# fjord_lbp = "fjorR4ubuG42xkRUF6SrA1hKkb1T4LqgfupE1mPLK4K"
# ---------------------------------------------------------------------------

# Local ---------------------------------------------------------------------
[programs.localnet]
fjord_lbp = "9yf45kAVeaaaAqBewB6fLX4ie5qBC2vWwqiBhNQayvWq"
# ---------------------------------------------------------------------------

[registry]
url = "https://api.apr.dev"

[provider]
# Path to the wallet keypair to use for deployments/upgrades

# Production ----------------------------------------------------------------
# wallet = "./deployment-keypair/production/id.json" 
# cluster = "Mainnet"
# ---------------------------------------------------------------------------

# Dev -----------------------------------------------------------------------
# wallet = "./deployment-keypair/development/id.json"
# cluster = "Devnet"
# ---------------------------------------------------------------------------

# Local ---------------------------------------------------------------------
wallet = "./deployment-keypair/local/id.json"
cluster = "Localnet"
# ---------------------------------------------------------------------------

[workspace]
types = "types"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
upgradeable = true